<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$scheme_modules['-menu-'] = Array('name'        => 'menu',
                            'type'              => 'MyISAM',
                            'tables'            => Array('-menu_info-',
                                                         '-menu_structure-',
                                                         '-menu_place-',
                                                         '-menu_content-',
                                                         '-menu_theme-',
                                                         ),
                             'alias'            => 'Меню',
                             'short_description'      => 'Меню',
                             'description'      => 'Управление меню',
                             'folder'           => 'menu',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'menu',
                             'sort'             => 1,
                             );
$scheme_modules['-site-'] = Array('name'       => 'site',
                            'type'             => 'MyISAM',
                            'tables'           => Array( '-site_www-',
                                                         '-site_group-',
                                                         ),
                             'alias'            => 'Сайты',
                             'short_description'      => 'Сайты',
                             'description'      => 'Управление сайтами',
                             'folder'           => 'site',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'site',
                             'sort'             => 2,
                             );
$scheme_modules['-pages-'] = Array('name'       => 'pages',
                            'type'              => 'MyISAM',
                            'tables'            => Array( '-pages-',
                                                          '-contents-',
                                                        ),
                             'alias'            => 'Страницы',
                             'short_description'      => 'Страницы',
                             'description'      => 'Управление страницами',
                             'folder'           => 'pages',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'pages',
                             'sort'             => 3,
                             );
$scheme_modules['-contents-'] = Array('name'    => 'contents',
                            'type'              => 'MyISAM',
                            'tables'            => Array( '-contents-',
                                                        ),
                             'alias'            => 'Содержимое',
                             'short_description'      => 'Содержимое',
                             'description'      => 'Управление содержимым',
                             'folder'           => 'contents',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'contents',
                             'sort'             => 4,
                             );
$scheme_modules['-katalog-'] = Array('name'    => 'katalog',
                            'type'              => 'MyISAM',
                            'tables'            => Array( '-auto-',
                                                          '-model_auto-',
                                                          '-make-',
                                                          '-category-',
                                                          '-photo_auto-',
                                                          '-photo_model-',
                                                          '-auto_buy-',
                                                          '-currency-',

                                                        ),
                             'alias'            => 'katalog',
                             'short_description'      => 'Каталог',
                             'description'      => 'Каталог техники',
                             'folder'           => 'katalog',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'katalog',
                             'sort'             => 4,
                             );
$scheme_modules['-auth-'] = Array('name'    => 'auth',
                            'type'              => 'MyISAM',
                            'tables'            => Array(
                                                        ),
                             'alias'            => 'ion_auth',
                             'short_description'      => 'Пользователи',
                             'description'      => 'Аутентификация пользователей',
                             'folder'           => 'auth',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'auth',
                             'sort'             => 4,
                             );
$scheme_modules['-language-'] = Array('name'    => 'language',
                            'type'              => 'MyISAM',
                            'tables'            => Array('-language-',
                                                        ),
                             'alias'            => 'language',
                             'short_description'      => 'Языки',
                             'description'      => 'Мультиязычность',
                             'folder'           => 'language',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'language',
                             'sort'             => 5,
                             );
$scheme_modules['-feedback-'] = Array('name'    => 'feedback',
                            'type'              => 'MyISAM',
                            'tables'            => Array('-feedback_message-',
                                                         '-feedback_theme-',
                                                        ),
                             'alias'            => 'feedback',
                             'short_description'      => 'Обратная связь',
                             'description'      => 'Обратная связь',
                             'folder'           => 'feedback',
                             'start_method'     => 'admin_index',
                             'start_controller' => 'feedback',
                             'sort'             => 6,
                             );
$scheme_modules['-news-'] =     Array('name'    => 'news',
                            'type'              => 'MyISAM',
                            'tables'            => Array('-news-',
                                                         '-news_pages_name-',
                                                         '-news_contents-',
                                                         '-news_category-',
                                                         '-news_category_name-',
                                                         '-news_category_contents-',
                                                        ),
                             'alias'            => 'news',
                             'short_description'      => 'Новости',
                             'description'      => 'Новости',
                             'folder'           => 'news',
                             'start_method'     => 'admin_route',
                             'start_controller' => 'news',
                             'sort'             => 7,
                             );
$scheme_modules['-lands-'] =     Array('lands'    => 'lands',
                            'type'              => 'MyISAM',
                            'tables'            => Array('-lands_objects-',
                                                         '-lands_categories-',
                                                         '-lands_communications-',
                                                         '-lands_contacts-',
                                                         '-lands_currency-',
                                                         '-lands_directions-',
                                                         '-lands_groups-',
                                                         '-lands_objects_communications-',
                                                         '-lands_permitted_use-',
                                                         '-lands_photos-',
                                                         '-lands_regions-',
                                                        ),
                             'alias'            => 'lands',
                             'short_description'      => 'Недвижимость',
                             'description'      => 'Недвижимость',
                             'folder'           => 'lands',
                             'start_method'     => 'admin_route',
                             'start_controller' => 'lands',
                             'sort'             => 8,
                             );




