<?php

/*
 *  Маршрутизация для модуля
 *
 *
 */
$config = array(
       'route' =>  array(
              'admin' =>  array(
                     '!' => array(
                     		'index_name' => '11',
                     		'index' => array(),
                     		'start_segment' => 4,
                     		'module' => 'duc',
                     		'controller' => 'duc',
                     		'method' => 'index',
                     		'control_uri' => 'admin',
                     ),
                     'groups' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'groups',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                     ),
                     /*
                     'object_list' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'object',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: lands_object_all',
                            'module' => 'lands',
                            'controller' => 'lands_objects',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'object',
                     ),
                     */
                     'teachers' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'teachers',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_teachers',
                            'module' => 'duc',
                            'controller' => 'duc_teachers',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'teachers_list' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'teachers',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_teachers',
                            'module' => 'duc',
                            'controller' => 'duc_teachers',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'teachers',
                     ),
                     'departments' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'departments',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_departments',
                            'module' => 'duc',
                            'controller' => 'duc_departments',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'directions' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'directions',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_directions',
                            'module' => 'duc',
                            'controller' => 'duc_directions',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'sections' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'sections',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_sections',
                            'module' => 'duc',
                            'controller' => 'duc_sections',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                     ),
                     'activities' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'activities',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_activities',
                            'module' => 'duc',
                            'controller' => 'duc_activities',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'qualifications' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'qualifications',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_qualifications',
                            'module' => 'duc',
                            'controller' => 'duc_qualifications',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'teachers',
                     ),
                     'ranks' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'ranks',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_ranks',
                            'module' => 'duc',
                            'controller' => 'duc_ranks',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'teachers',
                     ),

                     'concertmasters' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'concertmasters',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_concertmasters',
                            'module' => 'duc',
                            'controller' => 'duc_concertmasters',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'photos' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'photos',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_photos',
                            'module' => 'duc',
                            'controller' => 'duc_photos',
                            'method' => 'grid_admin_object',
                            'menu' => true,

                     ),
                     'photos_list' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'photos',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_photos_groups',
                            'module' => 'duc',
                            'controller' => 'duc_photos',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'photos',
                     ),
                     'photos_package' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'photos',
                                   'action' => 'package',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_photos_package',
                            'module' => 'duc',
                            'controller' => 'duc_photos',
                            'method' => 'tpl_package',
                            'menu' => true,
                            'parent' => 'photos',
                     ),


                     'addresses' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'addresses',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_addresses',
                            'module' => 'duc',
                            'controller' => 'duc_addresses',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => false,
                     ),
                     'schedules' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'schedules',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => false,
                     ),
                     'schedules_list' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'schedules',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_schedule',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'schedules',
                     ),
                     'numgroups' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'numgroups',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_numgroups',
                            'module' => 'duc',
                            'controller' => 'duc_numgroups',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'schedules',
                     ),
                     'durations' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'durations',
                                   'action' => 'all',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_durations',
                            'module' => 'duc',
                            'controller' => 'duc_durations',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => false,
                     ),

                     'object_id' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'object',
                                   'action' => 'all',
                                   'id' => true,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: lands_object_edit',
                            'module' => 'lands',
                            'controller' => 'lands_objects',
                            'method' => '_html_admin_object_id',
                            'arg' => 'index:id',
                            'menu' => false,
                            'parent' => 'object_list',
                     ),
                     'setting' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'set',
                                   'action' => 'all',
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_setting',
                            'module' => 'duc',
                            'controller' => 'duc_setting',
                            'method' => '_html_admin_object_id',
                            'menu' => true,
                     ),
                     'setting_object' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'set',
                                   'action' => 'object',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_object_setting',
                            'module' => 'duc',
                            'controller' => 'duc',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'setting',
                     ),
                     'setting_admin' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'set',
                                   'action' => 'admin',
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_setting_admin',
                            'module' => 'duc',
                            'controller' => 'duc',
                            'method' => '_html_admin_object_id',
                            'menu' => true,
                            'parent' => 'setting',
                     ),
                     'setting_photos' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'set',
                                   'action' => 'photos',
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_setting_photos',
                            'module' => 'duc',
                            'controller' => 'duc_settings',
                            'method' => 'tpl_photos',
                            'menu' => true,
                            'parent' => 'setting',
                     ),
                     'setting_user' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'set',
                                   'action' => 'user',
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_setting_user',
                            'module' => 'duc',
                            'controller' => 'duc_admin_object_id',
                            'method' => '_html_admin_object_id',
                            'menu' => true,
                            'parent' => 'setting',
                     ),
                     /*
                     'category' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'category',
                                   'action' => 'all',
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: lands_category',
                            'module' => 'lands',
                            'controller' => 'lands_categories',
                            'method' => 'grid_admin_object',
                            'menu' => true,
                            'parent' => 'object_plots',
                     ),
                     */

              ),
              'ajax' =>  array(
                     '!' => array(
                     		'index_name' => '1',
                     		'index' => array(),
                     		'start_segment' => 4,
                     		'module' => 'duc',
                     		'controller' => 'duc',
                     		'method' => 'index',
                     		'control_uri' => 'admin',
                     ),
                     'uploads' =>  array(
                            'module' => 'lands',
                            'controller' => 'lands_photos',
                            'method' => 'upload_images_object',
                     ),
                     'print_images' =>  array(
                            'module' => 'lands',
                            'controller' => 'lands_photos',
                            'method' => 'print_images_object',
                     ),
                     'teachers_foto_delete' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                  'menu' => 'teachers',
                                   'action' => 'delete_foto',
                                   'id' => false,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_teachers',
                            'module' => 'duc',
                            'controller' => 'duc_teachers',
                            'method' => 'delete_foto',
                            //'arg' => array('index:object'),
                            //'parent' => 'teachers_list',
                            //'menu' => true,
                     ),
                     'photos_package_action' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'photos',
                                   'action' => 'act_package',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_photos_package',
                            'module' => 'duc',
                            'controller' => 'duc_photos',
                            'method' => 'action_package',
                            //'menu' => true,
                            //'parent' => 'photos',
                     ),
                     'action_photos_resize' =>  array(
                            'index_name' => 'object',
                            'index' =>  array(
                                   'menu' => 'photos',
                                   'action' => 'act_resize',
                                   'id' => false,
                            ),
                            'start_segment' => 4,
                            'name' => 'lang: duc_photos_resize',
                            'module' => 'duc',
                            'controller' => 'duc_photos',
                            'method' => 'action_resize',
                            //'menu' => true,
                            //'parent' => 'photos',
                     ),
               ),
               'user' =>  array(
                     '!' => array(
                     		'index_name' => '1',
                     		'index' => array(),
                     		'start_segment' => 2,
                     		'module' => 'duc',
                     		'controller' => 'duc',
                     		'method' => 'index',
                     		'control_uri' => false,
                     ),
                     'groups_list' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'groups',
                                   'object' => false,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_groups_list',
                            'menu' => true,
                     ),
                     'groups_id' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'groups',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_groups_id',
                            'arg' => array('index:object'),
                            'parent' => 'groups_list',
                            'menu' => true,
                     ),
                     'teacher_list' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'teachers',
                                   'object' => false,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_teachers',
                            'module' => 'duc',
                            'controller' => 'duc_teachers',
                            'method' => 'tpl_teachers_list',
                            'menu' => true,
                     ),

                     'teachers_id' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'teachers',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_teachers',
                            'module' => 'duc',
                            'controller' => 'duc_teachers',
                            'method' => 'tpl_teachers_id',
                            'arg' => array('index:object'),
                            'parent' => 'teachers_list',
                            'menu' => true,
                     ),
                     'schedules_list' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'schedules',
                                   'object' => false,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'tpl_schedules_list',
                            'menu' => true,
                     ),
                     'schedules_group' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'schedules_group',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'tpl_schedules_group',
                            'arg' => array('index:object'),
                            'parent' => 'schedules_list',
                            'menu' => true,
                     ),
                     'schedules_groupname' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'schedules_groupname',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'tpl_schedules_groupname',
                            'arg' => array('index:object'),
                            'parent' => 'schedules_list',
                            'menu' => true,
                     ),
                     'schedules_teacher' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'schedules_teacher',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'tpl_schedules_teacher',
                            'arg' => array('index:object'),
                            'parent' => 'schedules_list',
                            'menu' => true,
                     ),
                     'schedules_department' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'schedules_department',
                                   'object' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_schedules',
                            'module' => 'duc',
                            'controller' => 'duc_schedules',
                            'method' => 'tpl_schedules_department',
                            'arg' => array('index:object'),
                            'parent' => 'schedules_list',
                            'menu' => true,
                     ),
                     'mskobr' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr',
                                   'object' => false,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr',
                            'menu' => true,
                     ),
                     'mskobr_groups' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr_groups',
                                   'object' => false,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr_groups_list',
                            'menu' => true,
                     ),
                     /*
                     'mskobr_direction' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr_directions',
                                   'object' => true,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr_groups_direction',
                            'arg' => array('index:object'),
                            'menu' => true,
                     ),
                     */
                     'mskobr_direction_paid' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr_directions',
                                   'object' => true,
                                   'page' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr_groups_direction',
                            'arg' => array('index:object','index:page'),
                            'menu' => true,
                     ),
                     /*
                     'mskobr_department' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr_departmentsaa',
                                   'object' => true,

                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr_groups_department',
                            'arg' => array('index:object'),
                            'menu' => true,
                     ),
                     */
                     'mskobr_department_paid' =>  array(
                            'index_name' => 'user_objects',
                            'index' =>  array(
                                   'name' => 'mskobr_departments',
                                   'object' => true,
                                   'page' => true,
                            ),
                            'start_segment' => 2,
                            'name' => 'lang: duc_groups',
                            'module' => 'duc',
                            'controller' => 'duc_groups',
                            'method' => 'tpl_mskobr_groups_department',
                            'arg' => array('index:object','index:page'),
                            'menu' => true,
                     ),
               ),

       ),
       'control_uri' => 'admin',

);

