<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$scheme_base['-f_menu_info-'] = Array( 'id' => Array( 'name' => 'id',
                                                     'type' => 'int',
                                                     'long' => '7',
                                                     'null' => 'NOT NULL',
                                                     'default' => '',
                                                     'index' => '',
                                                     'extra' => 'auto_increment',
                                                     'foreign key' => ''
                                                    ),
                                       'name' => Array( 'name' => 'name',
                                                        'type' => 'char',
                                                        'long' => '100',
                                                        'null' => 'NOT NULL',
                                                        'default' => '',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'form' => array('name' => 'меню', 'check' => 'name_space', 'checkbox' => '0'),
                                                        'foreign key' => ''
                                                       ),
                                       'uri' => Array( 'name' => 'uri',
                                                        'type' => 'char',
                                                        'long' => '150',
                                                        'null' => 'NOT NULL',
                                                        'default' => '',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'form' => array('name' => 'сайт', 'checked' => '1'),
                                                        'foreign key' => ''
                                                       ),
                                       'show_menu' => Array( 'name' => 'show_menu',
                                                        'type' => 'tinyint',
                                                        'long' => '1',
                                                        'null' => 'NOT NULL',
                                                        'default' => '0',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'link' => array('name' => 'ссылка', 'number' => '7', 'checkbox' => '1'),
                                                        'form' => array('name' => 'показать', 'check' => 'numeric', 'checkbox' => '0'),
                                                        'foreign key' => ''
                                                       ),
                                       'id_site' => Array( 'name' => 'id_site',
                                                        'type' => 'int',
                                                        'long' => '5',
                                                        'null' => 'NULL',
                                                        'default' => '',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'foreign key' => 'site_www'
                                                       ),
                                       'id_menu_theme' => Array( 'name' => 'id_menu_theme',
                                                        'type' => 'SMALLINT',
                                                        'long' => '5',
                                                        'null' => 'NOT NULL',
                                                        'default' => '',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'foreign key' => ''
                                                       ),
                                       'img_menu' => Array( 'name' => 'img_menu',
                                                        'type' => 'char',
                                                        'long' => '100',
                                                        'null' => 'NOT NULL',
                                                        'default' => '',
                                                        'index' => '',
                                                        'extra' => '',
                                                        'foreign key' => ''
                                                       ),

                            );
$scheme_base['-f_menu_structure-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '7',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_menu_info' => Array( 'name' => 'id_menu_info',
                                                                'type' => 'int',
                                                                'long' => '7',
                                                                'null' => 'NOT NULL',
                                                                'default' => 'NULL',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'menu_info'
                                                               ),
                                               'id_menu_place' => Array( 'name' => 'id_menu_place',
                                                                'type' => 'int',
                                                                'long' => '7',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'menu_place'
                                                               ),
                                               'id_site' => Array( 'name' => 'id_site',
                                                                'type' => 'int',
                                                                'long' => '5',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'site_www'
                                                               ),
                                               'id_parrent' => Array( 'name' => 'id_parrent',
                                                                'type' => 'int',
                                                                'long' => '7',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'menu_sort' => Array( 'name' => 'menu_sort',
                                                                'type' => 'SMALLINT',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_site_www-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '7',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'url' => Array( 'name' => 'url',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_group' => Array( 'name' => 'id_group',
                                                                'type' => 'int',
                                                                'long' => '4',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'site_group'
                                                               ),

                            );
$scheme_base['-f_site_group-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '4',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_menu_place-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '4',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_site' => Array( 'name' => 'id_site',
                                                                'type' => 'int',
                                                                'long' => '5',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'site_www'
                                                               ),

                            );
$scheme_base['-f_menu_content-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '8',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_menu_info' => Array( 'name' => 'id_menu_info',
                                                                'type' => 'int',
                                                                'long' => '7',
                                                                'null' => 'NOT NULL',
                                                                'default' => 'NULL',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => 'menu_info'
                                                               ),
                                               'page_sort' => Array( 'name' => 'page_sort',
                                                                'type' => 'TINYINT',
                                                                'long' => '3',
                                                                'null' => 'NOT NULL',
                                                                'default' => '1',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'stop_word' => Array( 'name' => 'stop_word',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'title' => Array( 'name' => 'title',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'varchar',
                                                                'long' => '512',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'keywords' => Array( 'name' => 'keywords',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'content' => Array( 'name' => 'content',
                                                                'type' => 'text',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_menu_theme-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '4',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_pages-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '6',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'uri' => Array( 'name' => 'uri',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'form' => array('name' => 'показать', 'check' => 'numeric', 'checkbox' => '0'),
                                                                'foreign key' => ''
                                                               ),
                                              'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'tinyint',
                                                                'long' => '1',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'link' => array('name' => 'ссылка', 'number' => '7', 'checkbox' => '1'),
                                                                'form' => array('name' => 'показать', 'check' => 'numeric', 'checkbox' => '0'),
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_contents-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '6',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_pages' => Array( 'name' => 'id_pages',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_language' => Array( 'name' => 'id_language',
                                                                'type' => 'char',
                                                                'long' => '255',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'sort_id' => Array( 'name' => 'sort_pages',
                                                                'type' => 'int',
                                                                'long' => '4',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'title' => Array( 'name' => 'title',
                                                                'type' => 'varchar',
                                                                'long' => '255',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'varchar',
                                                                'long' => '400',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'keyworks' => Array( 'name' => 'keyworks',
                                                                'type' => 'varchar',
                                                                'long' => '200',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'content' => Array( 'name' => 'content',
                                                                'type' => 'text',
                                                                'long' => '',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );

$scheme_base['-f_auto-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_category' => Array( 'name' => 'id_category',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_model' => Array( 'name' => 'id_model',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_make' => Array( 'name' => 'id_make',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_currency' => Array( 'name' => 'id_currency',
                                                                'type' => 'smallint',
                                                                'long' => '3',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'smallint',
                                                                'long' => '1',
                                                                'null' => 'NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'varchar',
                                                                'long' => '100',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'year_make' => Array( 'name' => 'year_make',
                                                                'type' => 'YEAR',
                                                                'long' => '4',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'price' => Array( 'name' => 'price',
                                                                'type' => 'CHAR',
                                                                'long' => '20',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'mileage' => Array( 'name' => 'mileage',
                                                                'type' => 'CHAR',
                                                                'long' => '10',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'reserv' => Array( 'name' => 'reserv',
                                                                'type' => 'CHAR',
                                                                'long' => '10',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_create' => Array(
                                                                'name' => 'date_create',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_update' => Array(
                                                                'name' => 'date_update',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_create' => Array( 'name' => 'ip_create',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_update' => Array( 'name' => 'ip_update',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_model_auto-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'smallint',
                                                                'long' => '1',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'show_num' => Array( 'name' => 'show_num',
                                                                'type' => 'CHAR',
                                                                'long' => '3',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'logo' => Array( 'name' => 'logo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => '',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo2' => Array( 'name' => 'photo2',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'draw' => Array( 'name' => 'draw',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'short_description' => Array( 'name' => 'short_description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'detail' => Array( 'name' => 'detail',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'detail_table' => Array( 'name' => 'detail_table',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_create' => Array(
                                                                'name' => 'date_create',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_update' => Array(
                                                                'name' => 'date_update',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_create' => Array( 'name' => 'ip_create',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_update' => Array( 'name' => 'ip_update',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_make-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'smallint',
                                                                'long' => '1',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'logo' => Array( 'name' => 'logo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => '',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'CHAR',
                                                                'long' => '200',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'detail' => Array( 'name' => 'detail',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_create' => Array(
                                                                'name' => 'date_create',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_update' => Array(
                                                                'name' => 'date_update',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_create' => Array( 'name' => 'ip_create',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_update' => Array( 'name' => 'ip_update',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_category-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'smallint',
                                                                'long' => '1',
                                                                'null' => 'NOT NULL',
                                                                'default' => '0',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'logo' => Array( 'name' => 'logo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => '',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'CHAR',
                                                                'long' => '200',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'detail' => Array( 'name' => 'detail',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_create' => Array(
                                                                'name' => 'date_create',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_update' => Array(
                                                                'name' => 'date_update',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_create' => Array( 'name' => 'ip_create',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip_update' => Array( 'name' => 'ip_update',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_photo_auto-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_auto' => Array( 'name' => 'id_auto',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'CHAR',
                                                                'long' => '200',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo_main' => Array( 'name' => 'photo_main',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_add' => Array( 'name' => 'date_add',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip' => Array( 'name' => 'ip',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_photo_model-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_model' => Array( 'name' => 'id_model',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'CHAR',
                                                                'long' => '200',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo_main' => Array( 'name' => 'photo_main',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_add' => Array( 'name' => 'date_add',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip' => Array( 'name' => 'ip',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
$scheme_base['-f_auto_buy-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'id_category' => Array( 'name' => 'id_category',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_model' => Array( 'name' => 'id_model',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'id_make' => Array( 'name' => 'id_make',
                                                                'type' => 'smallint',
                                                                'long' => '5',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'varchar',
                                                                'long' => '100',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'year_make' => Array( 'name' => 'year_make',
                                                                'type' => 'YEAR',
                                                                'long' => '4',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'price' => Array( 'name' => 'price',
                                                                'type' => 'CHAR',
                                                                'long' => '20',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'mileage' => Array( 'name' => 'mileage',
                                                                'type' => 'CHAR',
                                                                'long' => '20',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'email' => Array( 'name' => 'email',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_add' => Array( 'name' => 'date_add',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip' => Array( 'name' => 'ip',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),

                            );
$scheme_base['-f_currency-'] = Array( 'id' => Array( 'name' => 'id',
                                                             'type' => 'int',
                                                             'long' => '5',
                                                             'null' => 'NOT NULL',
                                                             'default' => '',
                                                             'index' => '',
                                                             'extra' => 'auto_increment',
                                                             'foreign key' => ''
                                                            ),
                                               'show_i' => Array( 'name' => 'show_i',
                                                                'type' => 'tinyint',
                                                                'long' => '1',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name' => Array( 'name' => 'name',
                                                                'type' => 'CHAR',
                                                                'long' => '200',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'name_short' => Array( 'name' => 'name_short',
                                                                'type' => 'CHAR',
                                                                'long' => '4',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'photo' => Array( 'name' => 'photo',
                                                                'type' => 'CHAR',
                                                                'long' => '50',
                                                                'null' => 'NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'description' => Array( 'name' => 'description',
                                                                'type' => 'TINYTEXT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'date_add' => Array( 'name' => 'date_add',
                                                                'type' => 'TINYINT',
                                                                'long' => '',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),
                                               'ip' => Array( 'name' => 'ip',
                                                                'type' => 'CHAR',
                                                                'long' => '15',
                                                                'null' => 'NOT NULL',
                                                                'default' => '',
                                                                'index' => '',
                                                                'extra' => '',
                                                                'foreign key' => ''
                                                               ),


                            );
